### ISSUE TITLE
Update Endpoints to Support Role-Based Access for Groups

### ISSUE THREAD

**Issue by mohakcodes** [hokageCV/grudu-list#25]
### **Issue Summary:**
- **Issue 1:** Unable to access groups where the user is not the owner (only a member).
- **Issue 2:** Cannot determine whether to show/hide the edit and delete icons if the user is only an editor or viewer.

### **Objective:** 
Update the group membership handling to allow different roles (viewer/editor) and reflect these roles in the group's structure.

### **Proposed Changes:**

1. **Add Member Role Selection:**
   - Modify the body of endpoint `{{base_url}}/groups/{{group_id}}/memberships`
   - A dropdown will be introduced in the frontend to select the member's role (viewer/editor) during the process of adding a member to a group.
   - Update the payload to:
     ```json
     {"user_id": 10, "role": "editor or viewer"}
     ```
   - **Outcome:** This will address Issue 2 by providing the necessary data to determine the visibility of edit/delete icons.

2. **Reflect the Below Frontend `GroupType` Changes in the API Response**
    ```typescript
    // New type added
    type MemberType = {
        id: string;
        name: string;
        email: string;
        role: 'viewer' | 'editor';
    };
    
    export type GroupType = {
        id: string;
        name: string;
        owner: {
            id: string;
            name: string;
        };
        members: MemberType[]; // New line added
    };
    ```
    So update backend as follows-
    ```typescript
    //initially
    {
        "id": 25,
        "name": "kageyama's group 1",
        "owner": {
            "id": 4,
            "name": "kageyama"
        },
        "created_at": "2024-08-30T20:59:37.269Z",
        "updated_at": "2024-09-10T18:23:06.265Z"
    }
    
    //updated response
    {
        "id": 25,
        "name": "kageyama's group 1",
        "owner": {
            "id": 4,
            "name": "kageyama"
        },
        "members": [
            {
                "id": "1",
                "name": "User 1",
                "email": "user@gmail.com",
                "role": "viewer"
            },
            {
                "id": "2",
                "name": "User 2",
                "email": "user_2@gmail.com",
                "role": "editor"
            }
        ],
        "created_at": "2024-08-30T20:59:37.269Z",
        "updated_at": "2024-09-10T18:23:06.265Z"
    }
    ```

### **Tasks:**
- [ ] Modify the endpoint `{{base_url}}/groups/{{group_id}}/memberships` to accept the new `role` parameter.
- [ ] Test to ensure group responses now include the `members` array with role details.

**Comment by hokageCV** [comment]
> ensure group responses now include the members array with role details.
suppose a group has 1000 members, so should we send all the members in response?

**Comment by mohakcodes** [comment]
> Is user not able to open the group in which he is member but not owner?

Currently, there is no dedicated API endpoint to find the groups in which a user is added as a member.

In the current scenario, the members' details can be accessed using the `group ID` as an array at:
`baseurl/groups/{{groupID}}/memberships`

To display the groups (in the `AllGroups` component) where the user is a member, we would need to fetch all groups and, for each `group.id`, check the membership array. If a match is found, the group will be displayed. However, this approach has high complexity.

A more efficient solution would be to add a "members" array to the group type, which includes details about each user and their role (e.g., viewer/owner). 
This way, we can identify both the groups in which the user is a member and those where they are an owner in a single traversal. Additionally, role-based access can be implemented effectively.

**Comment by mohakcodes** [comment]
> suppose a group has 1000 members, so should we send all the members in response?

This aspect was not initially considered, and sending all members would not be efficient.

Currently, there are two endpoints in the backend for group access:

- baseurl/groups (to get all groups)
- baseurl/groups/23 (to get a specific group)

On the frontend, a filter is used to display only the groups where the user is the owner.

To improve this, we could add a new endpoint in the backend, such as:
baseurl/groups/23/user/{{user_ID}}.
This endpoint would return both the groups owned by the user and those the user has joined as a member.

**Comment by hokageCV** [comment]
Will update with following things 

1. An endpoint to get all groups where user is part of
2. Option to assign role while creating membership
3. An Endpoint to get all the members of group
